#!/usr/bin/env bash
case "$1" in
  lib)
      yarn build-lib
      cp README.md dist/mat-reduce
      pushd dist/mat-reduce
      npm publish
      popd
      ;;
  demo)
      yarn deploy-demo
      ;;
  *)
      echo $"Usage: $0 {lib|demo}"
      exit 1
 esac
